name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:

  linting-job:
    name: Lint HTML and CSS Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"

      - name: Lint CSS Files
        run: npx stylelint "**/*.css"

  
  build-job:
    name: Build the Website
    runs-on: ubuntu-latest
    needs: linting-job 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
